# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.10-slim

# set working directory
WORKDIR /app

# copy project files
COPY . .

# install dependencies
RUN pip install --no-cache-dir .

# expose no ports (stdio)

# default command to start the MCP server over stdio
CMD ["github-trending-mcp"]
